schema_version = "1.0.0"
id = "cut_sym"
name = "Cut Sym"
version = "0.0.3"
tagline = "Symmetrically cut mesh objects into two halves"
maintainer = "Wiffzackius"
type = "add-on"
tags = ["Mesh"]
blender_version_min = "4.2.0"
license = ["SPDX:GPL-3.0-or-later"]
website = "https://github.com/WifiLast/blender_split_symmetric"
copyright = [
    "2026 Martin St.",
]
